# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
use_frameworks! :linkage => :static

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo
  pod "es-cast-client-ios" , :path => "../"

end
